### ISSUE TITLE
readme incomplete

### ISSUE THREAD

**Issue by tofr** [bnidevs/NauTiLus#6]
Modify README.md in the root of your repo to display...
Your team name and roster
Your project title
Description of what your project presents to a user, and
**Description of how your project works**
**Launch instructions**

**Comment by bnidevs** [comment]
team name and roster check

**Comment by bnidevs** [comment]
project title check

**Comment by bnidevs** [comment]
launch instructions check

**Comment by bnidevs** [comment]
**Description of what your project presents to a user** should be moved out of background and into presentation

**Description of how your project works** should be added onto 

@slin15

**Comment by kyletau67** [comment]
**Description of what your project presents to a user** moved to presentation
**Description of how your project works** check
